### ISSUE TITLE
Question: Support for Mobile/Cordova Apps

### ISSUE THREAD

**Issue by jermahs** [okgrow/meteor-image-upload#11]
Hey this project seems really cool. I was wondering if it supports Mobile/Cordova. If it doesn't at the moment is it on the road map?

Cheers!

**Comment by pauldowman** [comment]
Yes it does. input type=file causes mobile browsers, including within Cordova, to show the camera and photo chooser. 

I should mention that we recently had a problem with Crosswalk on Android with Meteor 1.2, which seems to be a bug but might just have been a permissions thing. We fixed it by using the camera plugin, but I'll open an issue about that to document it at least.

**Comment by jermahs** [comment]
@pauldowman thanks for the timely response and the extra information!

**Comment by benstr** [comment]
@jpgilchrist here is a snippet showing our temporary workaround with the Crosswalk bug: https://github.com/okgrow/meteor-image-upload/issues/12

**Comment by jermahs** [comment]
@benstr awesome thank you
