### ISSUE TITLE
publicRead should be set at the collection level, not global

### ISSUE THREAD

**Issue by pauldowman** [okgrow/meteor-image-upload#5]
:neckbeard:

**Comment by deanrad** [comment]
I take it you're referring to https://github.com/okgrow/meteor-image-upload/blob/f63bfd49f501f2ac67b85d66538ee684122c515e/lib/image_upload.js#L33 ?

**Comment by pauldowman** [comment]
Yes this is definitely a bug. We've been meaning to change that, I guess we forgot to open an issue. Thanks for doing it.

**Comment by pauldowman** [comment]
Oh, haha this was opened by me. 😜. Oops.

**Comment by pauldowman** [comment]
Yes @deanius that's it.

**Comment by benstr** [comment]
refer to https://github.com/okgrow/meteor-image-upload/pull/10
